### ISSUE TITLE
django branch master renamed to main, needs to be accomodated

### ISSUE THREAD

**Issue by muskanvaswan** [django/django-asv#1]
As of March 9, 2021, Django renamed its master branch to main. 
[Here is the link to the conversation and announcement in the mailing list](https://groups.google.com/g/django-developers/c/tctDuKUGosc/m/vMCMTXqDDQAJ)

This is causing a variety of errors while run asv commands. Defaults for git commands etc need to be changed to fix this.

**Comment by smithdc1** [comment]
Thanks for the report. 

Would you like to have a go at fixing this? I think it should be a matter of finding the right setting in the JSON file?

**Comment by muskanvaswan** [comment]
I did try that, however, for some reason, it continues to flash the same errors saying unknown branch master in configuration. I even went so far as to do a full-text search on the entire project for master and replace it with main, it continues to flash the same error still. 
On looking into it further I think this is a default setting from airspeed velocity itself and we might have to wait on them to fix it. Not sure if there is a better solution to this. I faced pretty much the same issue with djangobench, because of the renaming as I was trying this out for GSoC.
any ideas on what could be done about this?

**Comment by smithdc1** [comment]
https://github.com/smithdc1/django-asv/blob/d3bc68686b0345b798fc285154cde1ef804df931/asv.conf.json#L33

Did you try uncommenting this line and changing it to `main`?

**Comment by muskanvaswan** [comment]
Yes, I did.

**Comment by smithdc1** [comment]
Hmm. Interesting. 

I had a look at the asv issues and couldn't see anything relevant there.

I'll try and have a look, it's been a while since I've looked at this properly. 

Thanks for your efforts here! 👍

**Comment by smithdc1** [comment]
Fixed in a065f1d22d64e2b1f554796299f0c36fa84d1341

@muskanvaswan -- do you want to have another look at this?

**Comment by muskanvaswan** [comment]
turns out, the reason that fix wasn't working for me was that it didn't recognise the change in the asv.conf.file. Deleting the cache folder did the trick eventually
