### ISSUE TITLE
Slow workflow; cache Django? 

### ISSUE THREAD

**Issue by smithdc1** [django/django-asv#46]
Hey @deepakdinesh1123 

Looking at https://github.com/smithdc1/django-asv/runs/6997443386?check_suite_focus=true we can see that only the benchmarks for the new test were run. However, this step still took 1 min 46s which _seems_ like rather a long time? 

I wonder if this is because of the time taken to download `django/django`. Maybe we could [cache](https://github.com/actions/cache) `django/django` to speed this up?

**Comment by carltongibson** [comment]
> I wonder if this is because of the time taken to download django/django. Maybe we could [cache](https://github.com/actions/cache) django/django to speed this up?

Cloning django/django takes _a while now_. I've successfully used the [`--depth`](https://git-scm.com/docs/git-clone#Documentation/git-clone.txt---depthltdepthgt) option to only pull one (or the few latest commits). Maybe this would be useful. 🤔 (Equally, maybe not if the caching works... 😜)
