### ISSUE TITLE
Moving repo to django org

### ISSUE THREAD

**Issue by deepakdinesh1123** [django/django-asv#56]
I have added the workflow to run the benchmarks when a pull request is labeled in the `django\django` repo [here](https://github.com/django/django/pull/15866), Mariusz Felisiak mentioned in a [comment](https://github.com/django/django/pull/15866/files/1045d009e652f45702edad866960ec52e8192549#r927350336) that moving this repo to the django organization would be better as the workflow wouldn't depend on any user repositories. 

Should the repo be moved?  Are there any changes that I need to make before moving?

**Comment by carltongibson** [comment]
Hey @deepakdinesh1123 — thanks for this. 

I have some preparatory work for releases next week, and then I will swing to this and look at what needs to happen. 
Thanks for your efforts!

**Comment by smithdc1** [comment]
Hi Carlton -- I had another look at the settings for this repo and can't see anywhere where I can grant extra privilages. Let me know if you need me to do anything to transfer the repo.

**Comment by carltongibson** [comment]
Thanks @smithdc1. It's been a busy week ... 😅. My plan is to pick this up next week.

**Comment by carltongibson** [comment]
Hey @smithdc1 — Right, so you have to go to the repo settings and then down the bottom there's a "Danger Zone" where the option to transfer is... 

<img width="829" alt="Screenshot 2022-08-10 at 11 40 43" src="https://user-images.githubusercontent.com/64686/183872741-7423aacb-89af-4900-8729-8286924fd576.png">

If you click that, hopefully I'll get a notification, and can pick up from there. 🤞

**Comment by smithdc1** [comment]
@carltongibson 
![image](https://user-images.githubusercontent.com/39445562/183875778-3caee58e-b0c2-4fa5-a3a9-eb98b001e561.png)

Maybe I could move to crispy-forms org and you could pick up from there?

**Comment by carltongibson** [comment]
@smithdc1 I've adjusted Django Org member permissions for the moment, can you try again? Thanks!

**Comment by smithdc1** [comment]
@carltongibson -- Done! 🎉

**Comment by carltongibson** [comment]
Well done. Thanks!
